## 00. Pytorch Fundamentals

## Resource Notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/


In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.4.1+cu121


In [ ]:
# Scalar Tensor

scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as Python int
scalar.item()

7

In [ ]:
# Vector Tensor

## Magnitude and direction
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR

TENSOR = torch.tensor([
    [
        [1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]
    ]
])
TENSOR


tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [ ]:
TENSOR2 = torch.tensor([
    [
        [1, 2, 3, 4],
        [4, 5, 6, 7],
        [1, 2, 3, 4],
        [1, 1, 1, 1],
        [1, 2, 1, 1]
    ],
    [
        [1, 1, 1, 1],
        [4, 5, 6, 7],
        [1, 2, 3, 4],
        [1, 1, 1, 1],
        [1, 2, 1, 1]
    ]
])
TENSOR2

tensor([[[1, 2, 3, 4],
         [4, 5, 6, 7],
         [1, 2, 3, 4],
         [1, 1, 1, 1],
         [1, 2, 1, 1]],

        [[1, 1, 1, 1],
         [4, 5, 6, 7],
         [1, 2, 3, 4],
         [1, 1, 1, 1],
         [1, 2, 1, 1]]])

In [ ]:
TENSOR2.ndim # should be 3

3

In [ ]:
TENSOR2.shape # should be .Size([2, 5, 4])

torch.Size([2, 5, 4])

In [ ]:
### Random tensors
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.3179, 0.0070, 0.7378, 0.8419],
        [0.7696, 0.0768, 0.3819, 0.5286],
        [0.8782, 0.9149, 0.6344, 0.2401]])

In [ ]:
random_tensor_2 = torch.rand(1)
random_tensor_2

tensor([0.6010])

In [ ]:
random_vector = torch.rand(2)
random_vector

tensor([0.9059, 0.6538])

In [ ]:
random_scalar = torch.rand(1) # this is actually a 1 dimensional vector
random_scalar
random_scalar.ndim

1

In [ ]:
my_scalar = torch.tensor(7)
my_scalar
my_scalar.ndim

0

In [ ]:
# Create a random tensor similar to shape to an image tensor

random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, coloru channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
t = torch.rand(224, 224, 3)
t

tensor([[[0.1368, 0.4523, 0.8685],
         [0.8596, 0.4415, 0.7058],
         [0.2141, 0.5340, 0.8030],
         ...,
         [0.0423, 0.4318, 0.7102],
         [0.1994, 0.6585, 0.5402],
         [0.6936, 0.9028, 0.5763]],

        [[0.3213, 0.6927, 0.5044],
         [0.0020, 0.5963, 0.1171],
         [0.7135, 0.5771, 0.9722],
         ...,
         [0.5225, 0.0561, 0.5779],
         [0.7006, 0.9501, 0.2556],
         [0.2219, 0.5447, 0.8222]],

        [[0.3703, 0.0096, 0.9933],
         [0.2413, 0.6911, 0.0214],
         [0.3571, 0.6142, 0.1642],
         ...,
         [0.6358, 0.5184, 0.8617],
         [0.4968, 0.6325, 0.1496],
         [0.9007, 0.2664, 0.4895]],

        ...,

        [[0.4972, 0.6983, 0.8094],
         [0.6650, 0.0285, 0.0449],
         [0.0430, 0.1778, 0.4163],
         ...,
         [0.0146, 0.2477, 0.9435],
         [0.9830, 0.5150, 0.9469],
         [0.8462, 0.6597, 0.1837]],

        [[0.7328, 0.9187, 0.4656],
         [0.4692, 0.8295, 0.0168],
         [0.

In [ ]:
t1 = torch.rand(2, 2, 2)
t1

tensor([[[0.3208, 0.7275],
         [0.4999, 0.3771]],

        [[0.6824, 0.1426],
         [0.1354, 0.9685]]])

In [ ]:
zeroes_tensor = torch.zeros(3, 4)
zeroes_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones_tensor = torch.ones(3, 4)
ones_tensor
ones_tensor.dtype

torch.float32

In [ ]:
# range of tensors

range_tensor = torch.arange(start=0, end=10, step=1)
range_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# tensors like
ten_zeroes = torch.zeros_like(input=range_tensor)
ten_zeroes

# We get the shape of `range_tensor` and use `zeros_like` whcih returns a tensor of zeroes using the sahpe of `range_tensor`

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
one_to_idk = torch.arange(start=0, end=1001,step=33)
one_to_idk

tensor([  0,  33,  66,  99, 132, 165, 198, 231, 264, 297, 330, 363, 396, 429,
        462, 495, 528, 561, 594, 627, 660, 693, 726, 759, 792, 825, 858, 891,
        924, 957, 990])

In [ ]:
zeroes = torch.zeros_like(input=one_to_idk)
zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0])

In [ ]:
# tensor Data types

# Flaot 32 tensor

float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # type (e.g. torch.float16 or torch.float32)
                               device=None, #
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
# Converting the float_32_tensor into a torch.float16
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

int_1_tensor = float_16_tensor.type(torch.int64)
int_2_tensor = float_32_tensor.type(torch.int64)

int_1_tensor * int_2_tensor

tensor([ 9, 36, 81])

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
## Getting information from tensors

## data type == tensor.dtype
## shape == tensor.shape
## device = tensor.device

In [ ]:
# Create a tensoor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.7723, 0.7815, 0.9919, 0.8126],
        [0.0839, 0.7773, 0.1102, 0.7309],
        [0.8221, 0.0511, 0.5325, 0.9918]])

In [ ]:
print(some_tensor)
print(f"Data Type of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.7723, 0.7815, 0.9919, 0.8126],
        [0.0839, 0.7773, 0.1102, 0.7309],
        [0.8221, 0.0511, 0.5325, 0.9918]])
Data Type of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manipulating tensors (operations)

Tensor operations:
* Addition
* subtraction
* Multiplication (element-wise)
* Divison
* Matrix multiplication

In [ ]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])

# Add 10 to it
tensor + 100

tensor([101, 102, 103])

In [ ]:
# Multiply by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# Try out pytorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
tensor = torch.zeros(size=[1, 2, 3])
tensor

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

In [ ]:
tensor = torch.tensor([1, 2, 3])
tensor

tensor([1, 2, 3])

In [ ]:
tensor.ndim

1

In [ ]:
### Matrix Multiplication

#### 1. Element-wise multiplication
2 * tensor



tensor([2, 4, 6])

In [ ]:

print(tensor, "*", tensor)
print(tensor*tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
tensor([1, 4, 9])


In [ ]:
#### 2. element-wise multiplication

#### (a dot b)
torch.matmul(tensor, tensor) # 1 + 4 + 9 = 14

tensor(14)

In [ ]:
## Rules of Matirx Multiplication

### 1. Inner Dimensions must match

### 2. Resulting matrix has the shape of the outer dimensions

### (2, 3) @ (3, 2) --> (2, 2)
### (3, 2) @ (3, 2) ---> error cause inner dimensions don't match
### (3, 2) @ (2, 3) --> (3, 3)
### (2, 10) @ (10, 2) --> (10, 10)

In [ ]:
torch.matmul(torch.rand(size=[3, 2]), torch.rand(size=[2, 3]))

tensor([[0.5248, 0.4191, 0.1123],
        [0.3015, 0.2465, 0.0638],
        [0.7497, 0.5471, 0.1671]])

In [ ]:
tensor_A = torch.tensor([
    [1, 2],
    [3, 4],
    [5, 6]
])

tensor_B = torch.tensor([
    [7, 10],
    [8, 11],
    [9, 12]
])

tensor_B.T.shape

# torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul

torch.Size([2, 3])

In [ ]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.min(x)

tensor(0)

In [ ]:
x.min()

tensor(0)

In [ ]:
torch.max(x) == x.max()

tensor(True)

In [ ]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [ ]:
torch.mean(x, dtype=torch.float32)

tensor(45.)

In [ ]:
x.type(torch.float32).mean()

tensor(45.)

In [ ]:
## Finding positioal min and max

x.argmin() # find that index 0 is the minimum value

tensor(0)

In [ ]:
x[x.argmax()]

tensor(90)

In [ ]:
x = torch.arange(1, 10, dtype=torch.float32)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
x_reshaped = x.reshape(1, 9)
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
my_tensor = torch.tensor([[1, 2, 3]])

my_tensor.shape

# now convert it to [3]

my_tensor.reshape(3)

tensor([1, 2, 3])

In [ ]:
z = x.view(1, 9)
x, z, z.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([1, 9]))

In [ ]:
x = torch.tensor([[1, 2, 3]])
z = x.view(3)
z[0] = 1000

print(x) # tensor([[1000, 2, 3]])
print(z) # tensor([1000, 2, 3])

tensor([[1000,    2,    3]])
tensor([1000,    2,    3])


In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([z, z, z, z], dim=0)
x_stacked

tensor([[1000,    2,    3],
        [1000,    2,    3],
        [1000,    2,    3],
        [1000,    2,    3]])

In [ ]:
# Squeeze
## removes all single dimensions from a target tensor

tensor1 = torch.tensor([[1, 2, 3]])
print(f"Unsqueezed tensor1: {tensor1}")
print(f"Unsqueezed tensor1 shape: {tensor1.shape}")
print(f"Squeezed tensor1: {tensor1.squeeze()}")
print(f"Squeezed tensor1 shape: {tensor1.squeeze().shape}")



Unsqueezed tensor1: tensor([[1, 2, 3]])
Unsqueezed tensor1 shape: torch.Size([1, 3])
Squeezed tensor1: tensor([1, 2, 3])
Squeezed tensor1 shape: torch.Size([3])


In [ ]:
tensor1 = torch.tensor([1, 2, 3])
print(f"Tensor: {tensor1} - shape = {tensor1.shape}")
unsqueezed_tensor1 = tensor1.unsqueeze(dim=0)
print(f"Tensor unsqueezed at dim=0: {unsqueezed_tensor1} - shape = {unsqueezed_tensor1.shape}")
unsqueezed_tensor2 = unsqueezed_tensor1.unsqueeze(dim=2)
print(f"Tensor unsqueezed at dim=0: {unsqueezed_tensor2} - shape = {unsqueezed_tensor2.shape}")

Tensor: tensor([1, 2, 3]) - shape = torch.Size([3])
Tensor unsqueezed at dim=0: tensor([[1, 2, 3]]) - shape = torch.Size([1, 3])
Tensor unsqueezed at dim=0: tensor([[[1],
         [2],
         [3]]]) - shape = torch.Size([1, 3, 1])


In [ ]:
# torch.pernute rearranges dimensions

tensor = torch.arange(0, 100)
print(tensor.shape)
new_tensor = tensor.reshape(2, 10, 5)
print(new_tensor.shape)
permuted = new_tensor.permute(2, 0, 1)
print(permuted.shape)

torch.Size([100])
torch.Size([2, 10, 5])
torch.Size([5, 2, 10])


In [ ]:
# Indexing

tensor = torch.rand(1, 3, 3)
tensor = tensor * 10
tensor = tensor.type(torch.int64)
tensor

tensor([[[8, 7, 1],
         [8, 5, 1],
         [3, 7, 2]]])

In [ ]:
tensor = tensor.squeeze()
tensor

tensor([[8, 7, 1],
        [8, 5, 1],
        [3, 7, 2]])

In [ ]:
tensor[:, 1]

tensor([7, 5, 7])

In [ ]:
# NumPy Array to Tensor

array = np.arange(1.0, 8.0)
array

array([1., 2., 3., 4., 5., 6., 7.])

In [ ]:
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array = tensor.numpy()
array

array([1., 2., 3., 4., 5., 6., 7.])

In [ ]:
# controled RNG

torch.manual_seed(42)
tensor_1 = torch.rand(2, 2)
print(tensor_1)

torch.manual_seed(42)
tensor_2 = torch.rand(2,2)
print(tensor_2)

print(tensor_1 == tensor_2)

tensor([[0.8823, 0.9150],
        [0.3829, 0.9593]])
tensor([[0.8823, 0.9150],
        [0.3829, 0.9593]])
tensor([[True, True],
        [True, True]])


In [ ]:
# GPUs = faster computation on hardware thanks to CUDA + NVIDIA + PyTorch working behind the scenes

## Easiest - Use Google Colab (could use Pro for free GPU
## Use Your Own GPU - takes a bit of setup and purchase GPU

!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
# GPU access with PyTorch
import torch
torch.cuda.is_available()

True

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print(torch.cuda.device_count)

<function device_count at 0x788b81b7be20>


In [ ]:
# Putting tensors and models onto GPU
tensor = torch.tensor([1,2,3])
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')